# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Prasanna Natarajan's code blog
email: prasanna@npras.in
description: > # this means to ignore newlines until "baseurl:"
  Seasoned Ruby on Rails and Devops Consultant. My number one goal is to help your Business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tech.npras.in" # the base hostname & protocol for your site
twitter_username: nprashere
github_username:  npras

# Build settings
markdown: kramdown
exclude: [Gemfile*, sample.rb]
destination: "./../../npras.in.sites/tech.npras.in"

permalink: /:title/


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true # All posts have comments enabled by default
